# Options: <https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=>

format_strings = true
hard_tabs = true
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
max_width = 79
use_small_heuristics = "max"
